name: CI Pipeline - Test

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]    
  workflow_dispatch:

# CONFIGURATION
env:
  NUGET_VERSION: '5.3.1'           # set this to the dot net version to use
  
jobs:
  build:

    runs-on: [ NS-DEV ]

    steps:
    #- uses: actions/checkout@v2

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}
    
    - name: Prep Nuget Source - Github Repo
      run: |          
        if (!!(nuget Sources List | ? { $_ -like "*githubRepo*"})){
            nuget Sources Remove -Name githubRepo
        }
        nuget Sources Add -Name githubRepo -Source "https://nuget.pkg.github.com/nirosanss/index.json" -UserName nirosanss -Password ${{ secrets.GITHUB_TOKEN }}
      
    #- name: Prep packages
    # run: nuget Sources Add -Name githubRepo -Source "https://nuget.pkg.github.com/nirosanss/index.json" -UserName nirosanss -Password ${{ secrets.GITHUB_TOKEN }}
      
    - name: Get Package Version No
      id: Version
      run: echo "::set-output name=VersionNo::%date:~10,4%.%date:~4,2%.%date:~7,2%.%time:~0,2%%time:~3,2%" #echo "::set-output name=VersionNo::$(date + '%Y.%m.%d')"  #'%Y.%m.%d.%H%M'
    
    - name: print Package Version No
      run: echo "Package Version No ${{ steps.Version.outputs.VersionNo }}"   
      
      
