name: CI Pipeline - Sonar

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]    
  workflow_dispatch:

# CONFIGURATION
env:
  NUGET_VERSION: '5.3.1'           # set this to the dot net version to use
  
jobs:
  build:

    runs-on: [ NS-DEV ]

    steps:
    - uses: actions/checkout@v2

    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}

    - name: NuGet - Restore Packages
      run: nuget restore .\SG-Clicker.sln

    - name: Run MSBuild - SG-Clicker.sln
      run: msbuild .\SG-Clicker.sln


    - name: Install SonarCloud scanner
      shell: powershell
      run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

    - name: Build and Sonar Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #  shell: powershell
    #  run: |
    #      .\.sonar\scanner\dotnet-sonarscanner begin /k:"ms-clicker" /o:"nirosans" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
    #      msbuild .\SG-Clicker.sln /t:Rebuild
    #      .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      run: |
          SonarScanner.MSBuild.exe begin /k:"ms-clicker" /o:"nirosans" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          MsBuild.exe .\SG-Clicker.sln /t:Rebuild
          SonarScanner.MSBuild.exe end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"