name: CI Pipeline - Test

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]    
  workflow_dispatch:

# CONFIGURATION
env:
  NUGET_VERSION: '5.3.1'           # set this to the dot net version to use
  
jobs:
  build:

    runs-on: [ NS-DEV ]

    steps:
    #- uses: actions/checkout@v2

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}
      
      
    - name: Prep packages
      run: nuget Sources Add -Name githubRepo -Source "https://nuget.pkg.github.com/nirosanss/index.json" -UserName nirosanss -Password ${{ secrets.GITHUB_TOKEN }}
      
      
      
      
