name: CI Pipeline - Sonar

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]    
  workflow_dispatch:

# CONFIGURATION
env:
  NUGET_VERSION: '5.3.1'           # set this to the dot net version to use
  
jobs:
  build:

    runs-on: [ NS-DEV ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Nuget
      uses: qtc6865/setup-nuget@main
      with:
        nuget-version: ${{ env.NUGET_VERSION}}

    - name: NuGet - Restore Packages
      run: nuget restore

    - name: Run MSBuild - SG-Clicker.sln
      run: msbuild .\SG-Clicker.sln
    
    - name: SonarQube Scan
      uses: qtc6865/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
